items:
- uid: System.Security
  commentId: N:System.Security
  id: System.Security
  children:
  - System.Security.AllowPartiallyTrustedCallersAttribute
  - System.Security.SecureString
  - System.Security.SecureStringMarshal
  - System.Security.SecurityCriticalAttribute
  - System.Security.SecurityException
  - System.Security.SecuritySafeCriticalAttribute
  - System.Security.SecurityTransparentAttribute
  - System.Security.VerificationException
  langs:
  - csharp
  - vb
  name: System.Security
  nameWithType: System.Security
  fullName: System.Security
  type: Namespace
  assemblies:
  - System.Security.SecureString
references:
- uid: System.Security.SecureString
  commentId: T:System.Security.SecureString
  parent: System.Security
  isExternal: false
  name: SecureString
  nameWithType: SecureString
  fullName: System.Security.SecureString
- uid: System.Security.SecureStringMarshal
  commentId: T:System.Security.SecureStringMarshal
  isExternal: false
  name: SecureStringMarshal
  nameWithType: SecureStringMarshal
  fullName: System.Security.SecureStringMarshal
- uid: System.Security.AllowPartiallyTrustedCallersAttribute
  commentId: T:System.Security.AllowPartiallyTrustedCallersAttribute
  isExternal: false
  name: AllowPartiallyTrustedCallersAttribute
  nameWithType: AllowPartiallyTrustedCallersAttribute
  fullName: System.Security.AllowPartiallyTrustedCallersAttribute
- uid: System.Security.SecurityCriticalAttribute
  commentId: T:System.Security.SecurityCriticalAttribute
  parent: System.Security
  isExternal: false
  name: SecurityCriticalAttribute
  nameWithType: SecurityCriticalAttribute
  fullName: System.Security.SecurityCriticalAttribute
- uid: System.Security.SecurityException
  commentId: T:System.Security.SecurityException
  isExternal: false
  name: SecurityException
  nameWithType: SecurityException
  fullName: System.Security.SecurityException
- uid: System.Security.SecuritySafeCriticalAttribute
  commentId: T:System.Security.SecuritySafeCriticalAttribute
  isExternal: false
  name: SecuritySafeCriticalAttribute
  nameWithType: SecuritySafeCriticalAttribute
  fullName: System.Security.SecuritySafeCriticalAttribute
- uid: System.Security.SecurityTransparentAttribute
  commentId: T:System.Security.SecurityTransparentAttribute
  isExternal: false
  name: SecurityTransparentAttribute
  nameWithType: SecurityTransparentAttribute
  fullName: System.Security.SecurityTransparentAttribute
- uid: System.Security.VerificationException
  commentId: T:System.Security.VerificationException
  isExternal: false
  name: VerificationException
  nameWithType: VerificationException
  fullName: System.Security.VerificationException
- uid: System.Security
  commentId: N:System.Security
  isExternal: false
  name: System.Security
  nameWithType: System.Security
  fullName: System.Security
